// ข้อมูลคำศัพท์ TOEIC (ภาษาอังกฤษ: คำแปลไทยที่ถูกต้อง, คำแปลไทยอื่นๆ ที่ผิด)
export const vocabulary = [
{ word: "Negotiate", correct: "เจรจา", others: ["ต่อรอง", "ปรึกษา", "เห็นด้วย"] },
{ word: "Facilitate", correct: "อำนวยความสะดวก", others: ["เร่งรัด", "ป้องกัน", "แก้ไข"] },
{ word: "Implement", correct: "นำไปปฏิบัติ", others: ["ปรับปรุง", "พิจารณา", "เสนอ"] },
{ word: "Allocate", correct: "จัดสรร", others: ["รวมกัน", "แจกจ่าย", "สร้าง"] },
{ word: "Comply", correct: "ปฏิบัติตาม", others: ["ร้องขอ", "ขัดแย้ง", "ยกเลิก"] },
{ word: "Revenue", correct: "รายได้", others: ["ค่าใช้จ่าย", "กำไร", "เงินทุน"] },
{ word: "Expenditure", correct: "ค่าใช้จ่าย", others: ["รายรับ", "เงินเดือน", "กำไร"] },
{ word: "Merger", correct: "การควบรวมกิจการ", others: ["การแยกตัว", "การลงทุน", "การประชุม"] },
{ word: "Acquisition", correct: "การเข้าซื้อกิจการ", others: ["การขาย", "การร่วมทุน", "การแข่งขัน"] },
{ word: "Discrepancy", correct: "ความคลาดเคลื่อน", others: ["ความถูกต้อง", "ความเหมาะสม", "ความชัดเจน"] },
{ word: "Prioritize", correct: "จัดลำดับความสำคัญ", others: ["ละเลย", "รอคอย", "เลื่อนออกไป"] },
{ word: "Sustainable", correct: "ยั่งยืน", others: ["ชั่วคราว", "ถาวร", "จำกัด"] },
{ word: "Prospective", correct: "ที่คาดหวังไว้", others: ["ที่ผ่านมา", "ปัจจุบัน", "ที่เสร็จสิ้นแล้ว"] },
{ word: "Mandatory", correct: "บังคับ", others: ["สมัครใจ", "ทางเลือก", "แนะนำ"] },
{ word: "Renovate", correct: "ปรับปรุงใหม่", others: ["สร้างใหม่", "รื้อถอน", "ซ่อมแซม"] },
{ word: "Initiate", correct: "ริเริ่ม", others: ["สิ้นสุด", "ยกเลิก", "ดำเนินการต่อ"] },
{ word: "Validate", correct: "ตรวจสอบความถูกต้อง", others: ["แก้ไข", "ปฏิเสธ", "ยกเลิก"] },
{ word: "Substitute", correct: "ทดแทน", others: ["เพิ่มเติม", "ลบออก", "ซ่อมแซม"] },
{ word: "Compensate", correct: "ชดเชย", others: ["ลงโทษ", "ให้รางวัล", "ละเว้น"] },
{ word: "Undertake", correct: "ดำเนินการ", others: ["เลิกล้ม", "เพิกเฉย", "ปฏิเสธ"] },
{ word: "Adequate", correct: "เพียงพอ", others: ["ขาดแคลน", "มากเกินไป", "ไม่เหมาะสม"] },
{ word: "Approve", correct: "อนุมัติ", others: ["ปฏิเสธ", "สงสัย", "วิจารณ์"] },
{ word: "Concurrently", correct: "พร้อมกัน", others: ["ตามลำดับ", "แยกกัน", "ทีละน้อย"] },
{ word: "Delegate", correct: "มอบหมาย", others: ["รับผิดชอบ", "ควบคุม", "เลื่อน"] },
{ word: "Enhance", correct: "ส่งเสริม", others: ["ลดลง", "ทำลาย", "ยับยั้ง"] },
{ word: "Exempt", correct: "ยกเว้น", others: ["รวม", "บังคับ", "จำกัด"] },
{ word: "Guarantee", correct: "รับประกัน", others: ["เสี่ยง", "สงสัย", "คาดเดา"] },
{ word: "Indicate", correct: "บ่งชี้", others: ["ปกปิด", "ละเลย", "ปฏิเสธ"] },
{ word: "Liable", correct: "มีแนวโน้มที่จะ", others: ["ไม่สามารถ", "เป็นไปไม่ได้", "ไม่น่าจะ"] },
{ word: "Optimize", correct: "ทำให้ดีที่สุด", others: ["ทำให้แย่ลง", "ทำให้ซับซ้อน", "ลดทอน"] },
{ word: "Perceive", correct: "รับรู้", others: ["เพิกเฉย", "เข้าใจผิด", "หลีกเลี่ยง"] },
{ word: "Prosper", correct: "เจริญรุ่งเรือง", others: ["ล้มเหลว", "ถดถอย", "หยุดนิ่ง"] },
{ word: "Refurbish", correct: "ปรับปรุงใหม่", others: ["ทำลาย", "สร้าง", "ซ่อมแซม"] },
{ word: "Scrutinize", correct: "พิจารณาอย่างละเอียด", others: ["มองข้าม", "อนุมัติ", "ละเลย"] },
{ word: "Speculate", correct: "คาดเดา", others: ["ยืนยัน", "พิสูจน์", "ตรวจสอบ"] },
{ word: "Substantial", correct: "มาก", others: ["น้อย", "เล็กน้อย", "ไม่สำคัญ"] },
{ word: "Tangible", correct: "จับต้องได้", others: ["นามธรรม", "ไม่ชัดเจน", "ไม่มีอยู่จริง"] },
{ word: "Undergo", correct: "ประสบ", others: ["หลีกเลี่ยง", "ปฏิเสธ", "ป้องกัน"] },
{ word: "Valid", correct: "ถูกต้อง", others: ["ผิดพลาด", "ไม่สมเหตุสมผล", "ไม่ถูกต้อง"] },
{ word: "Abundant", correct: "อุดมสมบูรณ์", others: ["ขาดแคลน", "หายาก", "จำกัด"] },
{ word: "Access", correct: "เข้าถึง", others: ["ปิดกั้น", "ปฏิเสธ", "หลีกเลี่ยง"] },
{ word: "Accommodate", correct: "อำนวยความสะดวก", others: ["ขัดขวาง", "ปฏิเสธ", "ยกเลิก"] },
{ word: "Adversely", correct: "ในทางลบ", others: ["ในทางบวก", "ในทางตรงกันข้าม", "อย่างเหมาะสม"] },
{ word: "Affiliate", correct: "ในเครือ", others: ["อิสระ", "คู่แข่ง", "พันธมิตร"] },
{ word: "Anticipate", correct: "คาดการณ์", others: ["ไม่คาดคิด", "สงสัย", "ปฏิเสธ"] },
{ word: "Appraise", correct: "ประเมิน", others: ["ละเลย", "สงสัย", "วิจารณ์"] },
{ word: "Arbitrary", correct: "ตามอำเภอใจ", others: ["มีเหตุผล", "เป็นธรรม", "สม่ำเสมอ"] },
{ word: "Attain", correct: "บรรลุ", others: ["ล้มเหลว", "หลีกเลี่ยง", "ปฏิเสธ"] },
{ word: "Authentic", correct: "ของแท้", others: ["ปลอม", "เลียนแบบ", "ไม่จริง"] },
{ word: "Authorize", correct: "อนุมัติ", others: ["ห้าม", "ปฏิเสธ", "ยกเลิก"] },
{ word: "Blueprint", correct: "พิมพ์เขียว", others: ["ผลิตภัณฑ์สำเร็จรูป", "ผลลัพธ์", "สรุป"] },
{ word: "Captivate", correct: "ทำให้หลงใหล", others: ["ทำให้เบื่อ", "ทำให้รำคาญ", "ผลักไส"] },
{ word: "Cohesion", correct: "การยึดเหนี่ยว", others: ["การแยกตัว", "ความขัดแย้ง", "ความแตกแยก"] },
{ word: "Conducive", correct: "เอื้อต่อ", others: ["ขัดขวาง", "เป็นอุปสรรค", "ไม่เหมาะสม"] },
{ word: "Consequence", correct: "ผลลัพธ์", others: ["สาเหตุ", "จุดเริ่มต้น", "ปัจจัย"] },
{ word: "Contend", correct: "โต้แย้ง", others: ["ยอมรับ", "เห็นด้วย", "สนับสนุน"] },
{ word: "Credible", correct: "น่าเชื่อถือ", others: ["ไม่น่าเชื่อถือ", "สงสัย", "เป็นเท็จ"] },
{ word: "Cumulative", correct: "สะสม", others: ["ลดลง", "ถดถอย", "แยกส่วน"] },
{ word: "Deduct", correct: "หักออก", others: ["เพิ่ม", "รวม", "บวก"] },
{ word: "Deficient", correct: "ขาดแคลน", others: ["สมบูรณ์", "เพียงพอ", "มากเกินไป"] },
{ word: "Diligent", correct: "ขยัน", others: ["ขี้เกียจ", "ประมาท", "ไม่รอบคอบ"] },
{ word: "Disseminate", correct: "เผยแพร่", others: ["ปิดบัง", "รวบรวม", "ยับยั้ง"] },
{ word: "Diverse", correct: "หลากหลาย", others: ["เหมือนกัน", "เป็นหนึ่งเดียว", "จำกัด"] },
{ word: "Eligible", correct: "มีสิทธิ์", others: ["ไม่มีสิทธิ์", "ไม่เหมาะสม", "ถูกปฏิเสธ"] },
{ word: "Encompass", correct: "ครอบคลุม", others: ["แยกออก", "ยกเว้น", "จำกัด"] },
{ word: "Endeavor", correct: "ความพยายาม", others: ["ความล้มเหลว", "การยอมแพ้", "ความเฉื่อยชา"] },
{ word: "Equitable", correct: "เป็นธรรม", others: ["ไม่ยุติธรรม", "ลำเอียง", "ไม่เท่าเทียม"] },
{ word: "Erode", correct: "กัดกร่อน", others: ["สร้าง", "เสริมสร้าง", "ปกป้อง"] },
{ word: "Evolve", correct: "พัฒนา", others: ["ถดถอย", "หยุดนิ่ง", "เสื่อมลง"] },
{ word: "Exacerbate", correct: "ทำให้แย่ลง", others: ["ทำให้ดีขึ้น", "แก้ไข", "บรรเทา"] },
{ word: "Exemplary", correct: "เป็นแบบอย่าง", others: ["ไม่ดี", "ธรรมดา", "ไม่เหมาะสม"] },
{ word: "Feasible", correct: "เป็นไปได้", others: ["เป็นไปไม่ได้", "ไม่สามารถทำได้", "ยาก"] },
{ word: "Fluctuate", correct: "ผันผวน", others: ["คงที่", "สม่ำเสมอ", "คงที่"] },
{ word: "Formulate", correct: "กำหนด", others: ["ทำลาย", "แก้ไข", "เพิกเฉย"] },
{ word: "Gratify", correct: "ทำให้พึงพอใจ", others: ["ทำให้ไม่พอใจ", "ทำให้รำคาญ", "ทำให้โกรธ"] },
{ word: "Hindrance", correct: "อุปสรรค", others: ["ผู้ช่วย", "สิ่งอำนวยความสะดวก", "การสนับสนุน"] },
{ word: "Imminent", correct: "จวนเจียน", others: ["ไกลออกไป", "ล่าช้า", "เป็นไปไม่ได้"] },
{ word: "Implicit", correct: "โดยนัย", others: ["ชัดเจน", "ตรงไปตรงมา", "ประกาศ"] },
{ word: "Incentive", correct: "สิ่งจูงใจ", others: ["อุปสรรค", "การลงโทษ", "การห้าม"] },
{ word: "Incur", correct: "ก่อให้เกิด", others: ["หลีกเลี่ยง", "ป้องกัน", "ยกเลิก"] },
{ word: "Indispensable", correct: "จำเป็นอย่างยิ่ง", others: ["ไม่จำเป็น", "สำรอง", "เสริม"] },
{ word: "Inequity", correct: "ความไม่เท่าเทียมกัน", others: ["ความเท่าเทียมกัน", "ความยุติธรรม", "ความเสมอภาค"] },
{ word: "Infringe", correct: "ละเมิด", others: ["เคารพ", "ปฏิบัติตาม", "ปกป้อง"] },
{ word: "Inherent", correct: "โดยธรรมชาติ", others: ["ภายนอก", "ไม่เกี่ยวข้อง", "ผิดปกติ"] },
{ word: "Initiative", correct: "ความคิดริเริ่ม", others: ["การตอบสนอง", "การเลียนแบบ", "การหยุดนิ่ง"] },
{ word: "Innumerable", correct: "นับไม่ถ้วน", others: ["น้อย", "จำกัด", "หายาก"] },
{ word: "Integrate", correct: "รวมเข้าด้วยกัน", others: ["แยกออก", "แบ่งแยก", "ทำลาย"] },
{ word: "Intervene", correct: "เข้าแทรกแซง", others: ["หลีกเลี่ยง", "เพิกเฉย", "ยอมรับ"] },
{ word: "Legitimate", correct: "ถูกต้องตามกฎหมาย", others: ["ผิดกฎหมาย", "ปลอม", "ไม่น่าเชื่อถือ"] },
{ word: "Lucrative", correct: "มีกำไร", others: ["ขาดทุน", "ไม่ทำกำไร", "ไร้ประโยชน์"] },
{ word: "Mitigate", correct: "บรรเทา", others: ["ทำให้แย่ลง", "เพิ่มขึ้น", "ทำลาย"] },
{ word: "Modulate", correct: "ปรับ", others: ["คงที่", "ไม่เปลี่ยนแปลง", "หยุด"] },
{ word: "Obligate", correct: "ผูกพัน", others: ["เป็นอิสระ", "ยกเว้น", "ละเว้น"] },
{ word: "Overhaul", correct: "ยกเครื่องใหม่", others: ["ซ่อมแซมเล็กน้อย", "ทาสี", "ทำความสะอาด"] },
{ word: "Paradigm", correct: "กระบวนทัศน์", others: ["รายละเอียด", "ข้อยกเว้น", "ความผิดปกติ"] },
{ word: "Pertain", correct: "เกี่ยวข้องกับ", others: ["ไม่เกี่ยวข้อง", "แยกต่างหาก", "ละเลย"] },
{ word: "Prevalent", correct: "แพร่หลาย", others: ["หายาก", "ไม่ปกติ", "เฉพาะที่"] },
{ word: "Proficient", correct: "เชี่ยวชาญ", others: ["ไม่เชี่ยวชาญ", "เริ่มต้น", "ไร้ฝีมือ"] },
{ word: "Prolong", correct: "ยืดเวลา", others: ["ลดลง", "สั้นลง", "จบลง"] },
{ word: "Prominent", correct: "โดดเด่น", others: ["ไม่สำคัญ", "ซ่อนเร้น", "ธรรมดา"] },
{ word: "Prospective", correct: "ที่คาดหวังไว้", others: ["ที่ผ่านมา", "ปัจจุบัน", "ที่เสร็จสิ้นแล้ว"] },
{ word: "Provoke", correct: "กระตุ้น", others: ["ระงับ", "บรรเทา", "ยับยั้ง"] },
{ word: "Reciprocate", correct: "ตอบแทน", others: ["รับ", "ให้", "ละเลย"] },
{ word: "Redundant", correct: "ซ้ำซ้อน", others: ["จำเป็น", "สำคัญ", "ไม่ซ้ำซ้อน"] },
{ word: "Reinforce", correct: "เสริมกำลัง", others: ["อ่อนแอลง", "ทำลาย", "ลดทอน"] },
{ word: "Relinquish", correct: "ละทิ้ง", others: ["ยึดติด", "รักษา", "ได้รับ"] },
{ word: "Resilient", correct: "ยืดหยุ่น", others: ["เปราะบาง", "อ่อนแอ", "แข็งกระด้าง"] },
{ word: "Revamp", correct: "ปรับปรุงใหม่", others: ["ทำให้แย่ลง", "คงเดิม", "ทำลาย"] },
{ word: "Robust", correct: "แข็งแกร่ง", others: ["อ่อนแอ", "เปราะบาง", "อ่อนแอ"] },
{ word: "Solicit", correct: "ขอร้อง", others: ["ปฏิเสธ", "ให้", "บังคับ"] },
{ word: "Stipulate", correct: "กำหนดเงื่อนไข", others: ["ละเลย", "ยกเว้น", "ยกเลิก"] },
{ word: "Subsidize", correct: "อุดหนุน", others: ["เก็บภาษี", "ลดราคา", "จำกัด"] },
{ word: "Sustain", correct: "รักษาไว้", others: ["ทำลาย", "ยุติ", "ลดลง"] },
{ word: "Terrestrial", correct: "บนบก", others: ["ในน้ำ", "ในอากาศ", "ในอวกาศ"] },
{ word: "Undermine", correct: "บ่อนทำลาย", others: ["เสริมสร้าง", "สนับสนุน", "ปกป้อง"] },
{ word: "Unprecedented", correct: "ไม่เคยมีมาก่อน", others: ["ปกติ", "ธรรมดา", "เคยมีมาแล้ว"] },
{ word: "Versatile", correct: "อเนกประสงค์", others: ["จำกัด", "เฉพาะทาง", "ไม่สามารถปรับเปลี่ยนได้"] },
{ word: "Vigorous", correct: "แข็งแรง", others: ["อ่อนแอ", "เฉื่อยชา", "ไม่แข็งแรง"] },
{ word: "Volatile", correct: "ผันผวน", others: ["มั่นคง", "คงที่", "ไม่เปลี่ยนแปลง"] },
{ word: "ipecac", correct: "คำแปลของ ipecac", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Chad", correct: "คำแปลของ Chad", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Tereshkova", correct: "คำแปลของ Tereshkova", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Kelley", correct: "คำแปลของ Kelley", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "cogwheel", correct: "คำแปลของ cogwheel", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "executing", correct: "คำแปลของ executing", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "boyishly", correct: "คำแปลของ boyishly", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "polygamy", correct: "คำแปลของ polygamy", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "layaway", correct: "คำแปลของ layaway", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "contributors", correct: "คำแปลของ contributors", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "axiomatically", correct: "คำแปลของ axiomatically", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "ignores", correct: "คำแปลของ ignores", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Starbucks", correct: "คำแปลของ Starbucks", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Luigi", correct: "คำแปลของ Luigi", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "completeness", correct: "คำแปลของ completeness", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "loadstone", correct: "คำแปลของ loadstone", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "cabby", correct: "คำแปลของ cabby", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "recovery", correct: "คำแปลของ recovery", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "prearranged", correct: "คำแปลของ prearranged", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "mandible", correct: "คำแปลของ mandible", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "shovelfuls", correct: "คำแปลของ shovelfuls", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "hunched", correct: "คำแปลของ hunched", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "fetlocks", correct: "คำแปลของ fetlocks", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "clavicles", correct: "คำแปลของ clavicles", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "portraiture", correct: "คำแปลของ portraiture", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "cuticle", correct: "คำแปลของ cuticle", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "staunchly", correct: "คำแปลของ staunchly", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "undercuts", correct: "คำแปลของ undercuts", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Scorpius", correct: "คำแปลของ Scorpius", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "baited", correct: "คำแปลของ baited", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "obtrudes", correct: "คำแปลของ obtrudes", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "IRS", correct: "คำแปลของ IRS", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "caromed", correct: "คำแปลของ caromed", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "carpeted", correct: "คำแปลของ carpeted", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "hankering", correct: "คำแปลของ hankering", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "mathematicians", correct: "คำแปลของ mathematicians", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "pits", correct: "คำแปลของ pits", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "mesmerized", correct: "คำแปลของ mesmerized", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "mishap", correct: "คำแปลของ mishap", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "skilled", correct: "คำแปลของ skilled", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "doled", correct: "คำแปลของ doled", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "GPS", correct: "คำแปลของ GPS", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Santana", correct: "คำแปลของ Santana", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "extenuate", correct: "คำแปลของ extenuate", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "perdition", correct: "คำแปลของ perdition", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "hindering", correct: "คำแปลของ hindering", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Alsace", correct: "คำแปลของ Alsace", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "girls", correct: "คำแปลของ girls", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "boils", correct: "คำแปลของ boils", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Delgado", correct: "คำแปลของ Delgado", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "unmemorable", correct: "คำแปลของ unmemorable", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "huddle", correct: "คำแปลของ huddle", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "external", correct: "คำแปลของ external", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "stumble", correct: "คำแปลของ stumble", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "trucking", correct: "คำแปลของ trucking", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "agreed", correct: "คำแปลของ agreed", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "humbler", correct: "คำแปลของ humbler", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "jejune", correct: "คำแปลของ jejune", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "gazelle", correct: "คำแปลของ gazelle", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "moochers", correct: "คำแปลของ moochers", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "crullers", correct: "คำแปลของ crullers", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "giantess", correct: "คำแปลของ giantess", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "notched", correct: "คำแปลของ notched", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "admit", correct: "คำแปลของ admit", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "indentation", correct: "คำแปลของ indentation", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "multifarious", correct: "คำแปลของ multifarious", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "thwarted", correct: "คำแปลของ thwarted", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "sensitives", correct: "คำแปลของ sensitives", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "barbs", correct: "คำแปลของ barbs", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "booted", correct: "คำแปลของ booted", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "moors", correct: "คำแปลของ moors", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "spiels", correct: "คำแปลของ spiels", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Colleen", correct: "คำแปลของ Colleen", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "lamppost", correct: "คำแปลของ lamppost", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "lank", correct: "คำแปลของ lank", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "biodiversity", correct: "คำแปลของ biodiversity", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "stereo", correct: "คำแปลของ stereo", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "treatable", correct: "คำแปลของ treatable", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "controverts", correct: "คำแปลของ controverts", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "undefinable", correct: "คำแปลของ undefinable", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "quays", correct: "คำแปลของ quays", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "series", correct: "คำแปลของ series", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "structures", correct: "คำแปลของ structures", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "radiator", correct: "คำแปลของ radiator", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "pulsate", correct: "คำแปลของ pulsate", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Scottie", correct: "คำแปลของ Scottie", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "laddering", correct: "คำแปลของ laddering", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "aristocracy", correct: "คำแปลของ aristocracy", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "larboard", correct: "คำแปลของ larboard", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "amenity", correct: "คำแปลของ amenity", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "leafiest", correct: "คำแปลของ leafiest", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "lawrencium", correct: "คำแปลของ lawrencium", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "budgets", correct: "คำแปลของ budgets", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "deeply", correct: "คำแปลของ deeply", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "moisturizes", correct: "คำแปลของ moisturizes", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "creature", correct: "คำแปลของ creature", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Sikhs", correct: "คำแปลของ Sikhs", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "sully", correct: "คำแปลของ sully", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "pedalling", correct: "คำแปลของ pedalling", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "chemotherapy", correct: "คำแปลของ chemotherapy", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "leaseholders", correct: "คำแปลของ leaseholders", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "sheen", correct: "คำแปลของ sheen", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Honeywell", correct: "คำแปลของ Honeywell", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "reprocess", correct: "คำแปลของ reprocess", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "cannily", correct: "คำแปลของ cannily", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "May", correct: "คำแปลของ May", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Ziploc", correct: "คำแปลของ Ziploc", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "swifter", correct: "คำแปลของ swifter", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "exhorts", correct: "คำแปลของ exhorts", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "interpret", correct: "คำแปลของ interpret", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "trundle", correct: "คำแปลของ trundle", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "proven", correct: "คำแปลของ proven", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "primitives", correct: "คำแปลของ primitives", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "deity", correct: "คำแปลของ deity", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "intrusive", correct: "คำแปลของ intrusive", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "minors", correct: "คำแปลของ minors", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "candied", correct: "คำแปลของ candied", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "bras", correct: "คำแปลของ bras", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "tanned", correct: "คำแปลของ tanned", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "mildest", correct: "คำแปลของ mildest", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "roundabout", correct: "คำแปลของ roundabout", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "gambits", correct: "คำแปลของ gambits", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "CRT", correct: "คำแปลของ CRT", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "fixation", correct: "คำแปลของ fixation", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "precondition", correct: "คำแปลของ precondition", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "casement", correct: "คำแปลของ casement", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "gnawn", correct: "คำแปลของ gnawn", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "montage", correct: "คำแปลของ montage", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "thermonuclear", correct: "คำแปลของ thermonuclear", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "blotching", correct: "คำแปลของ blotching", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "BASIC", correct: "คำแปลของ BASIC", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "scorers", correct: "คำแปลของ scorers", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Cyprus", correct: "คำแปลของ Cyprus", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "tackiest", correct: "คำแปลของ tackiest", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "segmented", correct: "คำแปลของ segmented", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "nontrivial", correct: "คำแปลของ nontrivial", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "demagogry", correct: "คำแปลของ demagogry", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "harvester", correct: "คำแปลของ harvester", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "liturgies", correct: "คำแปลของ liturgies", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "refusing", correct: "คำแปลของ refusing", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Saigon", correct: "คำแปลของ Saigon", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "tenures", correct: "คำแปลของ tenures", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Killeen", correct: "คำแปลของ Killeen", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "swanking", correct: "คำแปลของ swanking", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Prudence", correct: "คำแปลของ Prudence", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "fixable", correct: "คำแปลของ fixable", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "throe", correct: "คำแปลของ throe", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "cinchona", correct: "คำแปลของ cinchona", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "untrustworthy", correct: "คำแปลของ untrustworthy", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "decamp", correct: "คำแปลของ decamp", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "conglomerating", correct: "คำแปลของ conglomerating", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "mayor", correct: "คำแปลของ mayor", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Amharic", correct: "คำแปลของ Amharic", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "afloat", correct: "คำแปลของ afloat", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "calendaring", correct: "คำแปลของ calendaring", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "hardships", correct: "คำแปลของ hardships", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "rafters", correct: "คำแปลของ rafters", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "ramblers", correct: "คำแปลของ ramblers", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "metamorphose", correct: "คำแปลของ metamorphose", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Jansenist", correct: "คำแปลของ Jansenist", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "nibs", correct: "คำแปลของ nibs", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "groaned", correct: "คำแปลของ groaned", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "mule", correct: "คำแปลของ mule", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Laverne", correct: "คำแปลของ Laverne", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Leopold", correct: "คำแปลของ Leopold", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "willful", correct: "คำแปลของ willful", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Bisquick", correct: "คำแปลของ Bisquick", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "oops", correct: "คำแปลของ oops", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "enlightens", correct: "คำแปลของ enlightens", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "rhododendrons", correct: "คำแปลของ rhododendrons", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "claw", correct: "คำแปลของ claw", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "overstated", correct: "คำแปลของ overstated", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "caw", correct: "คำแปลของ caw", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "imperfections", correct: "คำแปลของ imperfections", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Sindbad", correct: "คำแปลของ Sindbad", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "bellies", correct: "คำแปลของ bellies", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "reasserting", correct: "คำแปลของ reasserting", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "canny", correct: "คำแปลของ canny", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "grandstanded", correct: "คำแปลของ grandstanded", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "uncorking", correct: "คำแปลของ uncorking", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "ballasts", correct: "คำแปลของ ballasts", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "determines", correct: "คำแปลของ determines", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Sana", correct: "คำแปลของ Sana", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "uncoupling", correct: "คำแปลของ uncoupling", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Alberto", correct: "คำแปลของ Alberto", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "accumulators", correct: "คำแปลของ accumulators", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "enfranchising", correct: "คำแปลของ enfranchising", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "synergy", correct: "คำแปลของ synergy", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "hilliest", correct: "คำแปลของ hilliest", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "levity", correct: "คำแปลของ levity", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Erwin", correct: "คำแปลของ Erwin", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "malingers", correct: "คำแปลของ malingers", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "reparations", correct: "คำแปลของ reparations", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "reformatories", correct: "คำแปลของ reformatories", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Saki", correct: "คำแปลของ Saki", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "diehard", correct: "คำแปลของ diehard", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "entwining", correct: "คำแปลของ entwining", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "probability", correct: "คำแปลของ probability", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "unbosoming", correct: "คำแปลของ unbosoming", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "centenarian", correct: "คำแปลของ centenarian", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "overlooks", correct: "คำแปลของ overlooks", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "ultimately", correct: "คำแปลของ ultimately", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "inexorable", correct: "คำแปลของ inexorable", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Frost", correct: "คำแปลของ Frost", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "striking", correct: "คำแปลของ striking", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "pucker", correct: "คำแปลของ pucker", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "courageously", correct: "คำแปลของ courageously", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "supersede", correct: "คำแปลของ supersede", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "legion", correct: "คำแปลของ legion", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "urged", correct: "คำแปลของ urged", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "openings", correct: "คำแปลของ openings", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "argon", correct: "คำแปลของ argon", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "carnations", correct: "คำแปลของ carnations", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "screenplays", correct: "คำแปลของ screenplays", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "discredit", correct: "คำแปลของ discredit", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "yak", correct: "คำแปลของ yak", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "aspens", correct: "คำแปลของ aspens", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "hobbyhorses", correct: "คำแปลของ hobbyhorses", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "scuppering", correct: "คำแปลของ scuppering", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "seedlings", correct: "คำแปลของ seedlings", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "garment", correct: "คำแปลของ garment", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "furiously", correct: "คำแปลของ furiously", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "strangest", correct: "คำแปลของ strangest", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "reawakened", correct: "คำแปลของ reawakened", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "anklets", correct: "คำแปลของ anklets", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "settable", correct: "คำแปลของ settable", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "creditor", correct: "คำแปลของ creditor", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "extravagances", correct: "คำแปลของ extravagances", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "astrophysicist", correct: "คำแปลของ astrophysicist", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "ancientest", correct: "คำแปลของ ancientest", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Knapp", correct: "คำแปลของ Knapp", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "frowzier", correct: "คำแปลของ frowzier", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "asexual", correct: "คำแปลของ asexual", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "dais", correct: "คำแปลของ dais", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "darkest", correct: "คำแปลของ darkest", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Aries", correct: "คำแปลของ Aries", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "waved", correct: "คำแปลของ waved", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "muffles", correct: "คำแปลของ muffles", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "propulsive", correct: "คำแปลของ propulsive", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Kazakh", correct: "คำแปลของ Kazakh", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "bethinks", correct: "คำแปลของ bethinks", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "unsubscribe", correct: "คำแปลของ unsubscribe", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "delusive", correct: "คำแปลของ delusive", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "bauxite", correct: "คำแปลของ bauxite", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "supervene", correct: "คำแปลของ supervene", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "starchier", correct: "คำแปลของ starchier", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "oversimplification", correct: "คำแปลของ oversimplification", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "graving", correct: "คำแปลของ graving", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Suriname", correct: "คำแปลของ Suriname", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "cache", correct: "คำแปลของ cache", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "rheumatism", correct: "คำแปลของ rheumatism", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "prepaying", correct: "คำแปลของ prepaying", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "virtuosity", correct: "คำแปลของ virtuosity", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "envy", correct: "คำแปลของ envy", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "sexiest", correct: "คำแปลของ sexiest", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "falls", correct: "คำแปลของ falls", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "veneer", correct: "คำแปลของ veneer", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "superscript", correct: "คำแปลของ superscript", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "wryness", correct: "คำแปลของ wryness", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "dozes", correct: "คำแปลของ dozes", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "quickened", correct: "คำแปลของ quickened", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "surfaced", correct: "คำแปลของ surfaced", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "matadors", correct: "คำแปลของ matadors", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Zionisms", correct: "คำแปลของ Zionisms", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "hamming", correct: "คำแปลของ hamming", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "cleanups", correct: "คำแปลของ cleanups", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "shivered", correct: "คำแปลของ shivered", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "baptize", correct: "คำแปลของ baptize", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "reverend", correct: "คำแปลของ reverend", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "plying", correct: "คำแปลของ plying", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "ballsy", correct: "คำแปลของ ballsy", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "pomegranate", correct: "คำแปลของ pomegranate", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "chapters", correct: "คำแปลของ chapters", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Wessex", correct: "คำแปลของ Wessex", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "extirpate", correct: "คำแปลของ extirpate", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "internationalism", correct: "คำแปลของ internationalism", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "deject", correct: "คำแปลของ deject", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "art", correct: "คำแปลของ art", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "birdieing", correct: "คำแปลของ birdieing", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Copperfield", correct: "คำแปลของ Copperfield", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "elixir", correct: "คำแปลของ elixir", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "deck", correct: "คำแปลของ deck", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "portrait", correct: "คำแปลของ portrait", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "jade", correct: "คำแปลของ jade", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "monkey", correct: "คำแปลของ monkey", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "washcloth", correct: "คำแปลของ washcloth", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "unsentimental", correct: "คำแปลของ unsentimental", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "upcoming", correct: "คำแปลของ upcoming", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "shacks", correct: "คำแปลของ shacks", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "magnify", correct: "คำแปลของ magnify", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "LGBT", correct: "คำแปลของ LGBT", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "vibrations", correct: "คำแปลของ vibrations", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "saw", correct: "คำแปลของ saw", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "underpays", correct: "คำแปลของ underpays", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "NORAD", correct: "คำแปลของ NORAD", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "leeks", correct: "คำแปลของ leeks", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "legally", correct: "คำแปลของ legally", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "residue", correct: "คำแปลของ residue", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Ramayana", correct: "คำแปลของ Ramayana", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "unwise", correct: "คำแปลของ unwise", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "drudges", correct: "คำแปลของ drudges", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "pumpkins", correct: "คำแปลของ pumpkins", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "blackthorn", correct: "คำแปลของ blackthorn", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "hydrometers", correct: "คำแปลของ hydrometers", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Henson", correct: "คำแปลของ Henson", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "nosed", correct: "คำแปลของ nosed", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "skirts", correct: "คำแปลของ skirts", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "quaintest", correct: "คำแปลของ quaintest", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "coiffure", correct: "คำแปลของ coiffure", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "middling", correct: "คำแปลของ middling", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "innovate", correct: "คำแปลของ innovate", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "slugs", correct: "คำแปลของ slugs", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "athletically", correct: "คำแปลของ athletically", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Ronnie", correct: "คำแปลของ Ronnie", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "underwrites", correct: "คำแปลของ underwrites", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "fairway", correct: "คำแปลของ fairway", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "tranquilizers", correct: "คำแปลของ tranquilizers", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "solstice", correct: "คำแปลของ solstice", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "grains", correct: "คำแปลของ grains", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "decentralization", correct: "คำแปลของ decentralization", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Cassandra", correct: "คำแปลของ Cassandra", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "snowstorms", correct: "คำแปลของ snowstorms", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "paralegals", correct: "คำแปลของ paralegals", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "borers", correct: "คำแปลของ borers", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "protesters", correct: "คำแปลของ protesters", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "octagonal", correct: "คำแปลของ octagonal", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "unfrequented", correct: "คำแปลของ unfrequented", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Georgian", correct: "คำแปลของ Georgian", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "closing", correct: "คำแปลของ closing", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "subversive", correct: "คำแปลของ subversive", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "crests", correct: "คำแปลของ crests", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "anemic", correct: "คำแปลของ anemic", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "altruist", correct: "คำแปลของ altruist", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "elusively", correct: "คำแปลของ elusively", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "QA", correct: "คำแปลของ QA", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "reviler", correct: "คำแปลของ reviler", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "pictured", correct: "คำแปลของ pictured", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "curtailed", correct: "คำแปลของ curtailed", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "impeccably", correct: "คำแปลของ impeccably", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "hideout", correct: "คำแปลของ hideout", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "rites", correct: "คำแปลของ rites", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "bulbous", correct: "คำแปลของ bulbous", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "redoing", correct: "คำแปลของ redoing", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "brusquely", correct: "คำแปลของ brusquely", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "mildness", correct: "คำแปลของ mildness", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "sideways", correct: "คำแปลของ sideways", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "clownishly", correct: "คำแปลของ clownishly", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "cinch", correct: "คำแปลของ cinch", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Caucasus", correct: "คำแปลของ Caucasus", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "fortissimo", correct: "คำแปลของ fortissimo", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "breakpoints", correct: "คำแปลของ breakpoints", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Magog", correct: "คำแปลของ Magog", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "taper", correct: "คำแปลของ taper", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "yuppie", correct: "คำแปลของ yuppie", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "strainer", correct: "คำแปลของ strainer", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "whoop", correct: "คำแปลของ whoop", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "workmanship", correct: "คำแปลของ workmanship", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "deranged", correct: "คำแปลของ deranged", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "curlicuing", correct: "คำแปลของ curlicuing", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "liter", correct: "คำแปลของ liter", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "wombats", correct: "คำแปลของ wombats", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "SOSes", correct: "คำแปลของ SOSes", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "versify", correct: "คำแปลของ versify", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "solace", correct: "คำแปลของ solace", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "flossing", correct: "คำแปลของ flossing", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "executrixes", correct: "คำแปลของ executrixes", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "snacks", correct: "คำแปลของ snacks", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "loan", correct: "คำแปลของ loan", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "ulcerated", correct: "คำแปลของ ulcerated", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "deplorably", correct: "คำแปลของ deplorably", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "performance", correct: "คำแปลของ performance", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "cockle", correct: "คำแปลของ cockle", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "reproachfully", correct: "คำแปลของ reproachfully", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Sodom", correct: "คำแปลของ Sodom", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "overcame", correct: "คำแปลของ overcame", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "doctrines", correct: "คำแปลของ doctrines", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "harmonious", correct: "คำแปลของ harmonious", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "AM", correct: "คำแปลของ AM", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "facelifts", correct: "คำแปลของ facelifts", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "flamingoes", correct: "คำแปลของ flamingoes", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "refuels", correct: "คำแปลของ refuels", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "indeterminately", correct: "คำแปลของ indeterminately", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Hecuba", correct: "คำแปลของ Hecuba", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Hebe", correct: "คำแปลของ Hebe", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "galloping", correct: "คำแปลของ galloping", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "loge", correct: "คำแปลของ loge", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "unsociable", correct: "คำแปลของ unsociable", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "mangle", correct: "คำแปลของ mangle", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "trumpery", correct: "คำแปลของ trumpery", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "happening", correct: "คำแปลของ happening", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Polynesians", correct: "คำแปลของ Polynesians", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "turquoises", correct: "คำแปลของ turquoises", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "joyed", correct: "คำแปลของ joyed", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "huskiest", correct: "คำแปลของ huskiest", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "aseptic", correct: "คำแปลของ aseptic", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "hoedown", correct: "คำแปลของ hoedown", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "invitingly", correct: "คำแปลของ invitingly", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "sermons", correct: "คำแปลของ sermons", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "tripod", correct: "คำแปลของ tripod", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "seaboards", correct: "คำแปลของ seaboards", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "incarcerates", correct: "คำแปลของ incarcerates", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "lens", correct: "คำแปลของ lens", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "less", correct: "คำแปลของ less", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "history", correct: "คำแปลของ history", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Stokes", correct: "คำแปลของ Stokes", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Petrarch", correct: "คำแปลของ Petrarch", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "crediting", correct: "คำแปลของ crediting", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "fondle", correct: "คำแปลของ fondle", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "perspires", correct: "คำแปลของ perspires", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "cacao", correct: "คำแปลของ cacao", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "cornerstone", correct: "คำแปลของ cornerstone", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Mimosa", correct: "คำแปลของ Mimosa", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "drawback", correct: "คำแปลของ drawback", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "frontally", correct: "คำแปลของ frontally", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "reformulates", correct: "คำแปลของ reformulates", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Azania", correct: "คำแปลของ Azania", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "quintessences", correct: "คำแปลของ quintessences", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "humanest", correct: "คำแปลของ humanest", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "abnormality", correct: "คำแปลของ abnormality", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "parthenogenesis", correct: "คำแปลของ parthenogenesis", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "oracles", correct: "คำแปลของ oracles", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "pigment", correct: "คำแปลของ pigment", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "arbutuses", correct: "คำแปลของ arbutuses", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "mixer", correct: "คำแปลของ mixer", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "ketogenic", correct: "คำแปลของ ketogenic", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "ostracized", correct: "คำแปลของ ostracized", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "exhibits", correct: "คำแปลของ exhibits", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Guam", correct: "คำแปลของ Guam", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "loutish", correct: "คำแปลของ loutish", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "pelvis", correct: "คำแปลของ pelvis", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "pithy", correct: "คำแปลของ pithy", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "youthful", correct: "คำแปลของ youthful", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "lusher", correct: "คำแปลของ lusher", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "murkier", correct: "คำแปลของ murkier", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "expansionist", correct: "คำแปลของ expansionist", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "folded", correct: "คำแปลของ folded", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "prejudgment", correct: "คำแปลของ prejudgment", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "chapel", correct: "คำแปลของ chapel", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "simulators", correct: "คำแปลของ simulators", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "baled", correct: "คำแปลของ baled", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "accuracy", correct: "คำแปลของ accuracy", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "antechambers", correct: "คำแปลของ antechambers", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "stuffings", correct: "คำแปลของ stuffings", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Carmen", correct: "คำแปลของ Carmen", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "tares", correct: "คำแปลของ tares", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Peg", correct: "คำแปลของ Peg", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "highjacked", correct: "คำแปลของ highjacked", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "moist", correct: "คำแปลของ moist", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "rusticity", correct: "คำแปลของ rusticity", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "fells", correct: "คำแปลของ fells", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "chinning", correct: "คำแปลของ chinning", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "syndicates", correct: "คำแปลของ syndicates", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "amorphously", correct: "คำแปลของ amorphously", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "parkways", correct: "คำแปลของ parkways", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "sticks", correct: "คำแปลของ sticks", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "habituates", correct: "คำแปลของ habituates", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "posterity", correct: "คำแปลของ posterity", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "fetus", correct: "คำแปลของ fetus", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "ingredient", correct: "คำแปลของ ingredient", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "disgustedly", correct: "คำแปลของ disgustedly", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "turboprop", correct: "คำแปลของ turboprop", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "redesigning", correct: "คำแปลของ redesigning", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Xanthippe", correct: "คำแปลของ Xanthippe", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "bandwidths", correct: "คำแปลของ bandwidths", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Carboniferous", correct: "คำแปลของ Carboniferous", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "mummification", correct: "คำแปลของ mummification", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Perls", correct: "คำแปลของ Perls", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "impetigo", correct: "คำแปลของ impetigo", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "hiccups", correct: "คำแปลของ hiccups", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "abstruse", correct: "คำแปลของ abstruse", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "pixel", correct: "คำแปลของ pixel", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "demoed", correct: "คำแปลของ demoed", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "LibreOffice", correct: "คำแปลของ LibreOffice", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "canvasses", correct: "คำแปลของ canvasses", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "switchable", correct: "คำแปลของ switchable", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Richter", correct: "คำแปลของ Richter", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "flashguns", correct: "คำแปลของ flashguns", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "x", correct: "คำแปลของ x", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Goth", correct: "คำแปลของ Goth", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "gaudily", correct: "คำแปลของ gaudily", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "kilograms", correct: "คำแปลของ kilograms", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "kings", correct: "คำแปลของ kings", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "diggers", correct: "คำแปลของ diggers", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "grill", correct: "คำแปลของ grill", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Ashkhabad", correct: "คำแปลของ Ashkhabad", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "adulterant", correct: "คำแปลของ adulterant", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "wedding", correct: "คำแปลของ wedding", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Ahmadabad", correct: "คำแปลของ Ahmadabad", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "broths", correct: "คำแปลของ broths", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Brandeis", correct: "คำแปลของ Brandeis", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "actualized", correct: "คำแปลของ actualized", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "wallpaper", correct: "คำแปลของ wallpaper", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Tim", correct: "คำแปลของ Tim", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "oligarchic", correct: "คำแปลของ oligarchic", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "polarized", correct: "คำแปลของ polarized", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Smetana", correct: "คำแปลของ Smetana", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Jayne", correct: "คำแปลของ Jayne", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "collared", correct: "คำแปลของ collared", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "stickiness", correct: "คำแปลของ stickiness", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "midland", correct: "คำแปลของ midland", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "suburbanites", correct: "คำแปลของ suburbanites", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "eyeballed", correct: "คำแปลของ eyeballed", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Hirobumi", correct: "คำแปลของ Hirobumi", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "merges", correct: "คำแปลของ merges", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "dealings", correct: "คำแปลของ dealings", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "woos", correct: "คำแปลของ woos", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "centimes", correct: "คำแปลของ centimes", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "dewlap", correct: "คำแปลของ dewlap", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "sunbathed", correct: "คำแปลของ sunbathed", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "PAC", correct: "คำแปลของ PAC", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Goiania", correct: "คำแปลของ Goiania", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "cleanness", correct: "คำแปลของ cleanness", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "breadbasket", correct: "คำแปลของ breadbasket", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "taint", correct: "คำแปลของ taint", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "imperturbability", correct: "คำแปลของ imperturbability", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "jimmying", correct: "คำแปลของ jimmying", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "abutment", correct: "คำแปลของ abutment", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "pickiest", correct: "คำแปลของ pickiest", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "permitting", correct: "คำแปลของ permitting", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "exudes", correct: "คำแปลของ exudes", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Marxist", correct: "คำแปลของ Marxist", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "legging", correct: "คำแปลของ legging", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "cheeriest", correct: "คำแปลของ cheeriest", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "sombre", correct: "คำแปลของ sombre", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "printer", correct: "คำแปลของ printer", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "illumination", correct: "คำแปลของ illumination", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Clemenceau", correct: "คำแปลของ Clemenceau", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "countrified", correct: "คำแปลของ countrified", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "rate", correct: "คำแปลของ rate", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "ratings", correct: "คำแปลของ ratings", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "differentiation", correct: "คำแปลของ differentiation", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "deprogramed", correct: "คำแปลของ deprogramed", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "shlocky", correct: "คำแปลของ shlocky", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "syphilitics", correct: "คำแปลของ syphilitics", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "retainers", correct: "คำแปลของ retainers", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "sleepwalk", correct: "คำแปลของ sleepwalk", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "distrusts", correct: "คำแปลของ distrusts", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "passage", correct: "คำแปลของ passage", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Segundo", correct: "คำแปลของ Segundo", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "ransomed", correct: "คำแปลของ ransomed", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "yearly", correct: "คำแปลของ yearly", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "tyrannical", correct: "คำแปลของ tyrannical", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "faking", correct: "คำแปลของ faking", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "chipped", correct: "คำแปลของ chipped", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "gratifying", correct: "คำแปลของ gratifying", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "maddest", correct: "คำแปลของ maddest", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "anticlimaxes", correct: "คำแปลของ anticlimaxes", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Bloomington", correct: "คำแปลของ Bloomington", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "boilings", correct: "คำแปลของ boilings", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "airworthy", correct: "คำแปลของ airworthy", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "seer", correct: "คำแปลของ seer", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "LBJ", correct: "คำแปลของ LBJ", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "happens", correct: "คำแปลของ happens", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "geodesics", correct: "คำแปลของ geodesics", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "honor", correct: "คำแปลของ honor", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "piggybacks", correct: "คำแปลของ piggybacks", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "backside", correct: "คำแปลของ backside", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "stifled", correct: "คำแปลของ stifled", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "denominations", correct: "คำแปลของ denominations", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "pebble", correct: "คำแปลของ pebble", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "aid", correct: "คำแปลของ aid", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "playoffs", correct: "คำแปลของ playoffs", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "linting", correct: "คำแปลของ linting", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "walkout", correct: "คำแปลของ walkout", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "guild", correct: "คำแปลของ guild", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "dauphins", correct: "คำแปลของ dauphins", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "supremacy", correct: "คำแปลของ supremacy", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "kneading", correct: "คำแปลของ kneading", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "fervency", correct: "คำแปลของ fervency", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "cripples", correct: "คำแปลของ cripples", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "bedridden", correct: "คำแปลของ bedridden", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "elder", correct: "คำแปลของ elder", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "oxidizer", correct: "คำแปลของ oxidizer", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "vole", correct: "คำแปลของ vole", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Antarctic", correct: "คำแปลของ Antarctic", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "GNP", correct: "คำแปลของ GNP", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "degrading", correct: "คำแปลของ degrading", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "unevenness", correct: "คำแปลของ unevenness", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Chicago", correct: "คำแปลของ Chicago", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "prefectures", correct: "คำแปลของ prefectures", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "neocon", correct: "คำแปลของ neocon", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "equivocally", correct: "คำแปลของ equivocally", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "inhalers", correct: "คำแปลของ inhalers", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Indian", correct: "คำแปลของ Indian", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "bodyguard", correct: "คำแปลของ bodyguard", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "anaconda", correct: "คำแปลของ anaconda", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "interlard", correct: "คำแปลของ interlard", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "cleaves", correct: "คำแปลของ cleaves", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "chinstraps", correct: "คำแปลของ chinstraps", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "bosh", correct: "คำแปลของ bosh", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "blender", correct: "คำแปลของ blender", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "markups", correct: "คำแปลของ markups", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "anoraks", correct: "คำแปลของ anoraks", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Farley", correct: "คำแปลของ Farley", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "cholesterol", correct: "คำแปลของ cholesterol", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "omelets", correct: "คำแปลของ omelets", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "beaned", correct: "คำแปลของ beaned", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "fascinations", correct: "คำแปลของ fascinations", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "tromps", correct: "คำแปลของ tromps", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "edema", correct: "คำแปลของ edema", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "crudity", correct: "คำแปลของ crudity", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Ferris", correct: "คำแปลของ Ferris", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Spaniard", correct: "คำแปลของ Spaniard", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "reared", correct: "คำแปลของ reared", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "examined", correct: "คำแปลของ examined", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "dint", correct: "คำแปลของ dint", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "slathers", correct: "คำแปลของ slathers", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "ligatured", correct: "คำแปลของ ligatured", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "impersonally", correct: "คำแปลของ impersonally", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "applauding", correct: "คำแปลของ applauding", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "boldface", correct: "คำแปลของ boldface", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "ripely", correct: "คำแปลของ ripely", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "touts", correct: "คำแปลของ touts", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "manicured", correct: "คำแปลของ manicured", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "naivety", correct: "คำแปลของ naivety", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "communistic", correct: "คำแปลของ communistic", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "alleviates", correct: "คำแปลของ alleviates", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "lathered", correct: "คำแปลของ lathered", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "head", correct: "คำแปลของ head", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "flurries", correct: "คำแปลของ flurries", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "coded", correct: "คำแปลของ coded", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "shrouds", correct: "คำแปลของ shrouds", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "personalizing", correct: "คำแปลของ personalizing", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "devoutly", correct: "คำแปลของ devoutly", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Hegelian", correct: "คำแปลของ Hegelian", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Buffalo", correct: "คำแปลของ Buffalo", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Ferraro", correct: "คำแปลของ Ferraro", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "syphoning", correct: "คำแปลของ syphoning", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "eccentric", correct: "คำแปลของ eccentric", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "obscener", correct: "คำแปลของ obscener", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "unhealthful", correct: "คำแปลของ unhealthful", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "papacy", correct: "คำแปลของ papacy", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "hoed", correct: "คำแปลของ hoed", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "audit", correct: "คำแปลของ audit", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "lampshade", correct: "คำแปลของ lampshade", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "discipline", correct: "คำแปลของ discipline", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "parables", correct: "คำแปลของ parables", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "hypertension", correct: "คำแปลของ hypertension", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "lecterns", correct: "คำแปลของ lecterns", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "whistling", correct: "คำแปลของ whistling", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "grossness", correct: "คำแปลของ grossness", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "feuds", correct: "คำแปลของ feuds", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Bonn", correct: "คำแปลของ Bonn", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Geminis", correct: "คำแปลของ Geminis", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "excitable", correct: "คำแปลของ excitable", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "unexpected", correct: "คำแปลของ unexpected", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "escape", correct: "คำแปลของ escape", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "numb", correct: "คำแปลของ numb", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "defoliates", correct: "คำแปลของ defoliates", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "reformulating", correct: "คำแปลของ reformulating", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "resells", correct: "คำแปลของ resells", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "slowpokes", correct: "คำแปลของ slowpokes", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "inquirers", correct: "คำแปลของ inquirers", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "nectar", correct: "คำแปลของ nectar", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "petrochemicals", correct: "คำแปลของ petrochemicals", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "handrails", correct: "คำแปลของ handrails", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "dared", correct: "คำแปลของ dared", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "barging", correct: "คำแปลของ barging", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "whitish", correct: "คำแปลของ whitish", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "elastic", correct: "คำแปลของ elastic", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "hydrocarbons", correct: "คำแปลของ hydrocarbons", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "incurably", correct: "คำแปลของ incurably", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "briskets", correct: "คำแปลของ briskets", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "imaginary", correct: "คำแปลของ imaginary", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "investigation", correct: "คำแปลของ investigation", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "disses", correct: "คำแปลของ disses", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "tasking", correct: "คำแปลของ tasking", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "jaded", correct: "คำแปลของ jaded", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "incisiveness", correct: "คำแปลของ incisiveness", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "scruffy", correct: "คำแปลของ scruffy", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "overcome", correct: "คำแปลของ overcome", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "cheesecake", correct: "คำแปลของ cheesecake", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "tactful", correct: "คำแปลของ tactful", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "muscat", correct: "คำแปลของ muscat", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "stooge", correct: "คำแปลของ stooge", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "denuding", correct: "คำแปลของ denuding", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "regretted", correct: "คำแปลของ regretted", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "streets", correct: "คำแปลของ streets", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "pearly", correct: "คำแปลของ pearly", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "advisor", correct: "คำแปลของ advisor", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Pigmies", correct: "คำแปลของ Pigmies", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "allusion", correct: "คำแปลของ allusion", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "adjusted", correct: "คำแปลของ adjusted", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "tocsin", correct: "คำแปลของ tocsin", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Picasso", correct: "คำแปลของ Picasso", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "enhancer", correct: "คำแปลของ enhancer", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "irregularity", correct: "คำแปลของ irregularity", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Ustinov", correct: "คำแปลของ Ustinov", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Lisbon", correct: "คำแปลของ Lisbon", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "former", correct: "คำแปลของ former", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "soppiest", correct: "คำแปลของ soppiest", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "mallard", correct: "คำแปลของ mallard", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "suffuse", correct: "คำแปลของ suffuse", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "clawing", correct: "คำแปลของ clawing", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "prefecture", correct: "คำแปลของ prefecture", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "frighteningly", correct: "คำแปลของ frighteningly", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "andante", correct: "คำแปลของ andante", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "ignominiously", correct: "คำแปลของ ignominiously", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "bisect", correct: "คำแปลของ bisect", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Christmases", correct: "คำแปลของ Christmases", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "megaphoned", correct: "คำแปลของ megaphoned", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "protractors", correct: "คำแปลของ protractors", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "navigability", correct: "คำแปลของ navigability", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "soils", correct: "คำแปลของ soils", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "quire", correct: "คำแปลของ quire", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "calking", correct: "คำแปลของ calking", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "collided", correct: "คำแปลของ collided", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "field", correct: "คำแปลของ field", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Muscat", correct: "คำแปลของ Muscat", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "demagogs", correct: "คำแปลของ demagogs", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "abnormal", correct: "คำแปลของ abnormal", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "stunning", correct: "คำแปลของ stunning", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Paderewski", correct: "คำแปลของ Paderewski", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "perfidies", correct: "คำแปลของ perfidies", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "interpreted", correct: "คำแปลของ interpreted", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "fancying", correct: "คำแปลของ fancying", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Dem", correct: "คำแปลของ Dem", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "extradite", correct: "คำแปลของ extradite", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "raunchy", correct: "คำแปลของ raunchy", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "sprinklers", correct: "คำแปลของ sprinklers", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "sandbags", correct: "คำแปลของ sandbags", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "dyspeptics", correct: "คำแปลของ dyspeptics", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "alphabetic", correct: "คำแปลของ alphabetic", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "sit", correct: "คำแปลของ sit", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "authored", correct: "คำแปลของ authored", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "acquires", correct: "คำแปลของ acquires", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "bootblack", correct: "คำแปลของ bootblack", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "buoyancy", correct: "คำแปลของ buoyancy", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "unmasking", correct: "คำแปลของ unmasking", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "bookies", correct: "คำแปลของ bookies", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "outsider", correct: "คำแปลของ outsider", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "appends", correct: "คำแปลของ appends", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "inconspicuous", correct: "คำแปลของ inconspicuous", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "options", correct: "คำแปลของ options", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "boots", correct: "คำแปลของ boots", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "pickpockets", correct: "คำแปลของ pickpockets", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "inscribed", correct: "คำแปลของ inscribed", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "springtime", correct: "คำแปลของ springtime", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "finises", correct: "คำแปลของ finises", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Len", correct: "คำแปลของ Len", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "crossly", correct: "คำแปลของ crossly", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "them", correct: "คำแปลของ them", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "relabelled", correct: "คำแปลของ relabelled", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "drops", correct: "คำแปลของ drops", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "infects", correct: "คำแปลของ infects", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Sunnyvale", correct: "คำแปลของ Sunnyvale", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Fuller", correct: "คำแปลของ Fuller", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "stoniest", correct: "คำแปลของ stoniest", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "moodiness", correct: "คำแปลของ moodiness", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Maude", correct: "คำแปลของ Maude", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "carnation", correct: "คำแปลของ carnation", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "whitewashing", correct: "คำแปลของ whitewashing", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Oct", correct: "คำแปลของ Oct", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "corporal", correct: "คำแปลของ corporal", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "googles", correct: "คำแปลของ googles", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Robbins", correct: "คำแปลของ Robbins", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "inefficiency", correct: "คำแปลของ inefficiency", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "reinserts", correct: "คำแปลของ reinserts", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "inveigles", correct: "คำแปลของ inveigles", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "foamy", correct: "คำแปลของ foamy", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "surveyors", correct: "คำแปลของ surveyors", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Reva", correct: "คำแปลของ Reva", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "rewindable", correct: "คำแปลของ rewindable", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Beirut", correct: "คำแปลของ Beirut", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "wallow", correct: "คำแปลของ wallow", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "felling", correct: "คำแปลของ felling", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "insurgence", correct: "คำแปลของ insurgence", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "memorize", correct: "คำแปลของ memorize", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "cruisers", correct: "คำแปลของ cruisers", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "debentures", correct: "คำแปลของ debentures", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "gadding", correct: "คำแปลของ gadding", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "combative", correct: "คำแปลของ combative", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "orators", correct: "คำแปลของ orators", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "refitted", correct: "คำแปลของ refitted", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Syriac", correct: "คำแปลของ Syriac", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "politicizes", correct: "คำแปลของ politicizes", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "propped", correct: "คำแปลของ propped", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "ones", correct: "คำแปลของ ones", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "unobserved", correct: "คำแปลของ unobserved", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Winkle", correct: "คำแปลของ Winkle", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "accuser", correct: "คำแปลของ accuser", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Dionne", correct: "คำแปลของ Dionne", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "retailing", correct: "คำแปลของ retailing", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "jujubes", correct: "คำแปลของ jujubes", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "twangs", correct: "คำแปลของ twangs", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "roundish", correct: "คำแปลของ roundish", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "bloomers", correct: "คำแปลของ bloomers", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "appropriating", correct: "คำแปลของ appropriating", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "dewier", correct: "คำแปลของ dewier", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "unhorses", correct: "คำแปลของ unhorses", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "surname", correct: "คำแปลของ surname", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "shooters", correct: "คำแปลของ shooters", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "saviour", correct: "คำแปลของ saviour", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "bevels", correct: "คำแปลของ bevels", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "instructs", correct: "คำแปลของ instructs", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "decorous", correct: "คำแปลของ decorous", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "gorgeous", correct: "คำแปลของ gorgeous", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "communes", correct: "คำแปลของ communes", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "dearness", correct: "คำแปลของ dearness", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "reproduction", correct: "คำแปลของ reproduction", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "obsessing", correct: "คำแปลของ obsessing", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "toad", correct: "คำแปลของ toad", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "rebutted", correct: "คำแปลของ rebutted", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "disguised", correct: "คำแปลของ disguised", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "jumps", correct: "คำแปลของ jumps", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "devalue", correct: "คำแปลของ devalue", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "befriend", correct: "คำแปลของ befriend", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "atonal", correct: "คำแปลของ atonal", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "hazy", correct: "คำแปลของ hazy", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "liquidizing", correct: "คำแปลของ liquidizing", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "guillotining", correct: "คำแปลของ guillotining", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "tribunals", correct: "คำแปลของ tribunals", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "endways", correct: "คำแปลของ endways", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "clumsier", correct: "คำแปลของ clumsier", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "axles", correct: "คำแปลของ axles", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "soothes", correct: "คำแปลของ soothes", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "keystrokes", correct: "คำแปลของ keystrokes", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "clayiest", correct: "คำแปลของ clayiest", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "woulds", correct: "คำแปลของ woulds", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "parka", correct: "คำแปลของ parka", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "romances", correct: "คำแปลของ romances", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "emoticon", correct: "คำแปลของ emoticon", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "improbabilities", correct: "คำแปลของ improbabilities", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Frisbee", correct: "คำแปลของ Frisbee", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "highlight", correct: "คำแปลของ highlight", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "bustle", correct: "คำแปลของ bustle", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Krakow", correct: "คำแปลของ Krakow", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "meridians", correct: "คำแปลของ meridians", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "crescendo", correct: "คำแปลของ crescendo", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "ageism", correct: "คำแปลของ ageism", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "redressed", correct: "คำแปลของ redressed", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "forking", correct: "คำแปลของ forking", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "lamp", correct: "คำแปลของ lamp", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "backdrops", correct: "คำแปลของ backdrops", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Assyria", correct: "คำแปลของ Assyria", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "condemnation", correct: "คำแปลของ condemnation", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "embellishment", correct: "คำแปลของ embellishment", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Golconda", correct: "คำแปลของ Golconda", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "chunk", correct: "คำแปลของ chunk", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "grebe", correct: "คำแปลของ grebe", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "FCC", correct: "คำแปลของ FCC", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "carats", correct: "คำแปลของ carats", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Dino", correct: "คำแปลของ Dino", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Rhineland", correct: "คำแปลของ Rhineland", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "inclemency", correct: "คำแปลของ inclemency", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "seaward", correct: "คำแปลของ seaward", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "foreground", correct: "คำแปลของ foreground", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "dropper", correct: "คำแปลของ dropper", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "imprecise", correct: "คำแปลของ imprecise", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Wilburn", correct: "คำแปลของ Wilburn", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "hulls", correct: "คำแปลของ hulls", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "excisions", correct: "คำแปลของ excisions", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "vanadium", correct: "คำแปลของ vanadium", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "ethnologist", correct: "คำแปลของ ethnologist", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "intestine", correct: "คำแปลของ intestine", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "exiling", correct: "คำแปลของ exiling", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "vaster", correct: "คำแปลของ vaster", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "hoary", correct: "คำแปลของ hoary", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "dilates", correct: "คำแปลของ dilates", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "barrels", correct: "คำแปลของ barrels", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "flap", correct: "คำแปลของ flap", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "convenience", correct: "คำแปลของ convenience", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "tinkle", correct: "คำแปลของ tinkle", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "Walter", correct: "คำแปลของ Walter", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "kleptomaniac", correct: "คำแปลของ kleptomaniac", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "expostulation", correct: "คำแปลของ expostulation", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "demeanor", correct: "คำแปลของ demeanor", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "vouches", correct: "คำแปลของ vouches", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "fixated", correct: "คำแปลของ fixated", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "anatomical", correct: "คำแปลของ anatomical", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "exacerbates", correct: "คำแปลของ exacerbates", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "conciliators", correct: "คำแปลของ conciliators", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "injure", correct: "คำแปลของ injure", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "undeniably", correct: "คำแปลของ undeniably", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "nonalcoholic", correct: "คำแปลของ nonalcoholic", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "noisemaker", correct: "คำแปลของ noisemaker", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "progress", correct: "คำแปลของ progress", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "septets", correct: "คำแปลของ septets", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "laryngitis", correct: "คำแปลของ laryngitis", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "scenario", correct: "คำแปลของ scenario", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
{ word: "dextrously", correct: "คำแปลของ dextrously", others: ["ตัวเลือก1", "ตัวเลือก2", "ตัวเลือก3"] },
];
